apiVersion: batch/v1
kind: Job
metadata:
  name: smplcal-job
spec:
  template:
    spec:
      containers:
      - name: smplcal-job
        image: yash5090/smplcal:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
