apiVersion: apps/v1
kind: Deployment
metadata:
  name: smplcal-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: smplcal
  template:
    metadata:
      labels:
        app: smplcal
    spec:
      containers:
        - name: smplcal
          image: yash5090/smplcal:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
